// Veriable & constant's

/* 
There are 3 types of veriaables in js 

1.var 
2. let 
3.const 

Variables are constant (storage areas) for data/text/value
Variable basically store ==> number /text and other data types 

*/ 

// 1.var 

//how to decaler a variables
// semi colons are optional in javascript 
var box = 1;
var box = 2;
var firstName = "kaif";
var lastName ='ansari';
var city = `Hyderabad`

console.log(box)
console.log(box)
console.log(firstName);
console.log(lastName);
console.log(city);
var collageName = "st joshaph";
console.log(collageName);
var age = 19;
var age = "19";
var phoneNumber = "+91 9849014287";
var favFood = "pizza";
console.log(age);
console.log(phoneNumber);
console.log(favFood);
